import type { NextPage } from 'next'
import Head from 'next/head'

import Page from '../components/Page'

import { GlobalStyles } from '../styles/GlobalStyles'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tesla UI Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page />
      <GlobalStyles />
    </div>
  )
}

export default Home
